steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
    waitFor: ['Build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Show Substitutions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          echo "--- Verifying Substitution Values ---"
          echo "SERVICE_NAME: ${_SERVICE_NAME}"
          echo "BOT_TOKEN Secret Name: ${_BOT_TOKEN}"
          echo "APP_TOKEN Secret Name: ${_APP_TOKEN}"
          echo "PING_URL Secret Name: ${_PING_URL}"
          echo "FLOW_API_KEY Secret Name: ${_FLOW_API_KEY}"
          echo "SLACK_SIGNING_SECRET: ${_SLACK_SIGNING_SECRET}"
          echo "------------------------------------"
    waitFor: ['Push']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--update-env-vars=BOT_NAME=${_BOT_NAME}'
      - >-
        --set-secrets=FLOW_API_KEY=projects/28513040513/secrets/${_FLOW_API_KEY}:latest
      - >-
        --set-secrets=BOT_TOKEN=projects/28513040513/secrets/${_BOT_TOKEN}:latest
      - >-
        --set-secrets=APP_TOKEN=projects/28513040513/secrets/${_APP_TOKEN}:latest
      - >-
        --set-secrets=PING_URL=projects/28513040513/secrets/${_PING_URL}:latest
      - >-
        --set-secrets=SLACK_SIGNING_SECRET=projects/28513040513/secrets/${_SLACK_SIGNING_SECRET}:latest
    id: Deploy
    entrypoint: gcloud
    waitFor: ['Show Substitutions']
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: boreal-conquest-452919-s4
  _PLATFORM: managed
  _SERVICE_NAME: bolt-app
  _TRIGGER_ID: e084cf9b-a519-4002-878c-9db87c51adf1
  _DEPLOY_REGION: us-central1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bolt-app
